import type { MockTelemetryStep } from "./types.js";

function buildTimestamp(baseTime: Date, minuteOffset: number): string {
  return new Date(baseTime.getTime() + minuteOffset * 60_000).toISOString();
}

export function createMockTelemetrySequence(
  baseTime: Date = new Date(),
): MockTelemetryStep[] {
  return [
    {
      label: "Departure parking",
      expectedPhase: "DEPARTURE_PARKING",
      telemetry: {
        capturedAt: buildTimestamp(baseTime, 0),
        latitude: 49.0097,
        longitude: 2.5479,
        altitudeFt: 0,
        groundspeedKts: 0,
        headingDeg: 270,
        verticalSpeedFpm: 0,
        onGround: true,
        fuelTotalKg: 6200,
        gearPercent: 100,
        flapsPercent: 0,
        parkingBrake: true,
      },
    },
    {
      label: "Pushback",
      expectedPhase: "PUSHBACK",
      telemetry: {
        capturedAt: buildTimestamp(baseTime, 2),
        latitude: 49.00965,
        longitude: 2.5477,
        altitudeFt: 0,
        groundspeedKts: 2,
        headingDeg: 260,
        verticalSpeedFpm: 0,
        onGround: true,
        fuelTotalKg: 6180,
        gearPercent: 100,
        flapsPercent: 0,
        parkingBrake: false,
      },
    },
    {
      label: "Taxi out",
      expectedPhase: "TAXI_OUT",
      telemetry: {
        capturedAt: buildTimestamp(baseTime, 6),
        latitude: 49.01,
        longitude: 2.55,
        altitudeFt: 0,
        groundspeedKts: 18,
        headingDeg: 270,
        verticalSpeedFpm: 0,
        onGround: true,
        fuelTotalKg: 6150,
        gearPercent: 100,
        flapsPercent: 5,
        parkingBrake: false,
      },
    },
    {
      label: "Takeoff",
      expectedPhase: "TAKEOFF",
      telemetry: {
        capturedAt: buildTimestamp(baseTime, 12),
        latitude: 49.02,
        longitude: 2.58,
        altitudeFt: 700,
        groundspeedKts: 155,
        headingDeg: 270,
        verticalSpeedFpm: 1600,
        onGround: false,
        fuelTotalKg: 6000,
        gearPercent: 40,
        flapsPercent: 10,
        parkingBrake: false,
      },
    },
    {
      label: "Climb",
      expectedPhase: "CLIMB",
      telemetry: {
        capturedAt: buildTimestamp(baseTime, 16),
        latitude: 49.3,
        longitude: 1.9,
        altitudeFt: 8000,
        groundspeedKts: 250,
        headingDeg: 290,
        verticalSpeedFpm: 1800,
        onGround: false,
        fuelTotalKg: 5700,
        gearPercent: 0,
        flapsPercent: 0,
        parkingBrake: false,
      },
    },
    {
      label: "Cruise",
      expectedPhase: "CRUISE",
      telemetry: {
        capturedAt: buildTimestamp(baseTime, 28),
        latitude: 50.0,
        longitude: 0.9,
        altitudeFt: 34000,
        groundspeedKts: 440,
        headingDeg: 300,
        verticalSpeedFpm: 20,
        onGround: false,
        fuelTotalKg: 5200,
        gearPercent: 0,
        flapsPercent: 0,
        parkingBrake: false,
      },
    },
    {
      label: "Descent",
      expectedPhase: "DESCENT",
      telemetry: {
        capturedAt: buildTimestamp(baseTime, 34),
        latitude: 50.25,
        longitude: 0.55,
        altitudeFt: 9000,
        groundspeedKts: 310,
        headingDeg: 305,
        verticalSpeedFpm: -1400,
        onGround: false,
        fuelTotalKg: 5050,
        gearPercent: 0,
        flapsPercent: 0,
        parkingBrake: false,
      },
    },
    {
      label: "Approach",
      expectedPhase: "APPROACH",
      telemetry: {
        capturedAt: buildTimestamp(baseTime, 40),
        latitude: 50.7,
        longitude: -0.2,
        altitudeFt: 2500,
        groundspeedKts: 180,
        headingDeg: 310,
        verticalSpeedFpm: -900,
        onGround: false,
        fuelTotalKg: 4700,
        gearPercent: 60,
        flapsPercent: 15,
        parkingBrake: false,
      },
    },
    {
      label: "Landing",
      expectedPhase: "LANDING",
      telemetry: {
        capturedAt: buildTimestamp(baseTime, 46),
        latitude: 51.47,
        longitude: -0.4543,
        altitudeFt: 0,
        groundspeedKts: 120,
        headingDeg: 270,
        verticalSpeedFpm: -200,
        onGround: true,
        fuelTotalKg: 4500,
        gearPercent: 100,
        flapsPercent: 30,
        parkingBrake: false,
      },
    },
    {
      label: "Taxi in",
      expectedPhase: "TAXI_IN",
      telemetry: {
        capturedAt: buildTimestamp(baseTime, 51),
        latitude: 51.471,
        longitude: -0.455,
        altitudeFt: 0,
        groundspeedKts: 18,
        headingDeg: 250,
        verticalSpeedFpm: 0,
        onGround: true,
        fuelTotalKg: 4350,
        gearPercent: 100,
        flapsPercent: 0,
        parkingBrake: false,
      },
    },
    {
      label: "Arrival parking",
      expectedPhase: "ARRIVAL_PARKING",
      telemetry: {
        capturedAt: buildTimestamp(baseTime, 58),
        latitude: 51.472,
        longitude: -0.456,
        altitudeFt: 0,
        groundspeedKts: 0,
        headingDeg: 180,
        verticalSpeedFpm: 0,
        onGround: true,
        fuelTotalKg: 4300,
        gearPercent: 100,
        flapsPercent: 0,
        parkingBrake: true,
      },
    },
  ];
}
