services:
  postgres:
    image: postgres:16-alpine
    container_name: va-postgres
    environment:
      POSTGRES_DB: va_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - va-postgres-data:/var/lib/postgresql/data

volumes:
  va-postgres-data:
